### ISSUE TITLE
Docs.rs documentation doesn't build

### ISSUE THREAD

**Issue by jounathaen** [stm32-rs/stm32f407g-disc#22]
I don't know anything about the build process on docs.rs. But the [logs](https://docs.rs/crate/stm32f407g-disc/0.4.0/builds/208564) suggest, that the thumbv7... target isn't installed.
I don't know if this now fixed by itself, otherwise I think the following section needs to be added to the `Cargo.toml` (but again, I've never published a crate on my own yet).

```toml
[package.metadata.docs.rs]
features = ["stm32f407", "rt"]
default-target = "x86_64-unknown-linux-gnu"
```
